[package]
name = "syscall_net"
version = "0.1.0"
edition = "2021"

authors = ["Youjie Zheng <zyj578335934@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

# default = ["ip", "arceos_api/net", "axfeat/net"]
default = ["arceos_api/net", "axfeat/net"]

# Networking
# ip = ["axnet/ip"]
dns = []

[dependencies]
axnet = { path = "../../../modules/axnet" }
axerrno = { path = "../../../crates/axerrno" }
axprocess = { path = "../../../modules/axprocess" }
axfs = { path = "../../../modules/axfs" }
axio = { path = "../../../crates/axio" }
axlog = { path = "../../../modules/axlog" }
axsync = { path = "../../../modules/axsync" }
num_enum = { version = "0.5.11", default-features = false }
syscall_utils = { path = "../syscall_utils" }
numeric-enum-macro = { git = "https://github.com/mexus/numeric-enum-macro" }
axfeat = { path = "../../../api/axfeat" }
arceos_api = { path = "../../../api/arceos_api" }
